### ISSUE TITLE
xrtood4-client

### ISSUE THREAD

**Issue by mtonjes** [treydock/puppet-osg#1]
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y list xrootd4-client' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: dell-community. Please verify its path and try again
Error: /Stage[main]/Osg::Wn/Package[xrootd-client]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y list xrootd4-client' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: dell-community. Please verify its path and try again
Notice: /Stage[main]/Osg::Wn/Anchor[osg::wn::end]: Dependency Package[xrootd-client] has failures: true
Warning: /Stage[main]/Osg::Wn/Anchor[osg::wn::end]: Skipping because of failed dependencies

**Comment by treydock** [comment]
Looks like an issue connecting to dell-community repo.

```Error: Cannot retrieve repository metadata (repomd.xml) for repository: dell-community. Please verify its path and try again```
